algo = input('Digite algo: ')
print('Tipo primitivo: ',type(algo))
print('É Númerico? ', algo.isnumeric())
print('É Alfabético? ', algo.isalpha())
print('É Alfanumérico? ', algo.isalnum())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
print('Só tem espaços? ', algo.isspace())
print('É decimal? ', algo.isdecimal())
print('É um dígito? ', algo.isdigit())
print('É um identificador? ', algo.isidentifier())
print('É imprimível? ', algo.isprintable())
print('É ASCII? ', algo.isascii())